locales:
    - de_DE.UTF-8
    - en_US.UTF-8
    - en_GB.UTF-8

default_locale: en_GB.UTF-8

timezone: Europe/Berlin

portage_overlays:
    - last-hope

base_packages:
    - app-admin/syslog-ng
    - sys-process/vixie-cron

boot_services:
    - sshd
    - vixie-cron
    - syslog-ng