locales:
    - de_DE.UTF-8
    - en_US.UTF-8
    - en_GB.UTF-8

default_locale: en_GB.UTF-8

timezone: Europe/Berlin

portage_overlays:
    - last-hope

base_packages:
    - app-admin/syslog-ng
    - sys-process/vixie-cron

boot_services:
    - sshd
    - vixie-cron
    - syslog-ng

DISTDIR: "/var/cache/distfiles"
CFLAGS: "-O2 -pipe"
DEFAULT_USE: mmx sse sse2 -X -gtk -gnome -qt -qt3 -qt4 -cups -alsa
MAKEOPTS: -j4 -l6
EMERGE_DEFAULT_OPTS: "--jobs=4 --load-average=6 --keep-going"
ACCEPT_LICENSE: "*"