- name: Enable locales
  lineinfile: dest=/etc/locale.gen line="{{item}}"
  with_items: locales
- command: locale-gen
- command: eselect locale set {{default_locale}}

- shell: grep "^CHOST=" /etc/portage/make.conf
  changed_when: False
  register: default_chost
- set_fact: chost="{{default_chost.stdout}}"

- name: Set use flags
  lineinfile: dest=/etc/portage/package.use/setup line="{{item}}" create=yes
  with_items: package_use

- name: Unkeyword portage-2.2.20
  lineinfile: dest=/etc/portage/package.accept_keywords line="=sys-apps/portage-2.2.20 ~{{ansible_userspace_architecture|replace('x86_64', 'amd64')}}" create=yes

- name: Update to >=sys-apps/portage-2.2.20"
  command: emerge '>=sys-apps/portage-2.2.20'

- name: write make.conf
  template: src=make.conf dest=/etc/portage/make.conf

- name: Set accept keywords
  lineinfile: dest=/etc/portage/package.accept_keywords line="{{item}}" create=yes
  with_items: package_accept_keywords

- name: Setup SSH key for portage
  file: dest=/var/tmp/portage/.ssh mode=0755 owner=portage group=portage state=directory

- name: Install SSH key for portage
  copy: src=portage_id_rsa dest=/var/tmp/portage/.ssh/id_rsa mode=0600 owner=portage group=portage


# we don't have equery (from gentoolkit) yet
- name: Install layman
  command: emerge app-portage/layman

- name: Sync overlays
  command: layman -S

- name: enable overlays
  fail: msg="FIXME"
  when: overlay_urls is defined

- name: Add overlays
  command: layman -a {{item}}
  with_items: overlays
  when: overlays is defined

- name: Add layman's source statement to make.conf
  lineinfile: dest=/etc/portage/make.conf line="source /var/lib/layman/make.conf"

- name: Re-emerge changeduse
  command: emerge {{remerge_packages|join(" ")}} --newuse --changed-use --update

- name: Install base packages
  command: emerge {{install_packages|join(" ")}}